application:
    service:
        someProp2: A property value (for undefined profile)
        anotherProp2: another property value (for undefined profile)

---

spring:
    profiles: development

application:
    service:
        someProp2: A property value (for undefined profile)
        anotherProp2: another property value (for undefined profile)


---

spring:
    profiles: production

application:
    service:
        someProp2: A property value (for undefined profile)
        anotherProp2: another property value (for undefined profile)

